version: '3.7'

services:
  db:
    image: mysql:8.0
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    restart: always
    environment:
      MYSQL_DATABASE: minsknews
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: wordpress

  wordpress:
    depends_on:
      - db
    image: wordpress:6.1.1-php7.4
    ports:
      - "3000:80"
    restart: always
    environment:
      WORDPRESS_DEBUG: 1
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: minsknews

    volumes:
      - ./wp/themes/ztml-theme:/var/www/html/wp-content/themes/ztml-theme
      - ./wp/plugins:/var/www/html/wp-content/plugins
      - ./wp/uploads:/var/www/html/wp-content/uploads
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
#      - ./logs:/var/www/html/wp-content/logs
#      - ./error-logging.ini:/usr/local/etc/php/conf.d/error-logging.ini











